### ISSUE TITLE
Loki with persistent volume claim

### ISSUE THREAD

**Issue by kmpartner** [digitalocean/marketplace-kubernetes#156]
Hi,
I tried to use digitalOcean one-click deployment of loki. After deployment on Kubernetes cluster, pods seem to work but persistent volume claim (pvc) not worked.

For me, pvc worked when installed loki by using helm chart with some --set options, not using yaml file in this repo.
How can I improve this repo with pvc and upgraded version of containers?

**Comment by paulanunda** [comment]
Thanks for the feedback (and apologies for the slow reply); the Loki 1-click now has persistence enabled.
