### ISSUE TITLE
Kubernetes Monitoring Stack PVC Support

### ISSUE THREAD

**Issue by imixtron** [digitalocean/marketplace-kubernetes#158]
Any plan for adding Persistence Volumes support for Kubernetes Monitoring Stack?

When installing using the one-click deployment, if there is any kind of disruption, all of the logs are deleted from prometheus-operator on pod restart. This defeats the purpose of having monitoring in the first place since we won't find out anything about the pre-crash state.

**Comment by saul-gush** [comment]
Yes this is important - any setting changes that are made are lost if the nodes are restarted.

**Comment by paulanunda** [comment]
@imixtron I've added a 10gb PVC to the Grafana deployment so that Grafana changes can be persisted. Logs aren't stored as part of the monitoring stack though.
