### ISSUE TITLE
Kubernetes Monitoring Stack - Insights page not updated

### ISSUE THREAD

**Issue by guybarrette** [digitalocean/marketplace-kubernetes#169]
When installing the advanced metrics in a K8s cluster using the following instructions, the Portal's Insights page display additional metrics.
https://www.digitalocean.com/docs/kubernetes/how-to/monitor-advanced/

After installing the Kubernetes Monitoring Stack, the Insights page does not display additional metrics and still prompts to get additional metrics.

![image](https://user-images.githubusercontent.com/1854284/96002507-2f890180-0e07-11eb-9a40-d1ccd4e22c29.png)

I would expect that after installing the Kubernetes Monitoring Stack, the Insights page would display the additional metrics.

**Comment by GregCKrause** [comment]
Out of curiosity, what are the statuses of your kube-scheduler and kube-controller-manager?

After forwarding my Prometheus Expression Browser (command below), I noticed alerts were firing for those two.
`kubectl -n prometheus-operator port-forward svc/prometheus-operator-prometheus 9090`

Not sure if this will help at all, just some (hopefully helpful) observations.

**Comment by paulanunda** [comment]
@guybarrette kube-state-metrics needs to be installed within the kube-system namespace for the metrics to show up on the dashboard. As of today, the monitoring stack doesn't do that, but I could see how that would make sense. Thanks for the feedback.

@GregCKrause thanks for the feedback, not sure why the alerts are firing. I'll look into it.
