### ISSUE TITLE
Monitoring stack failing to install - Kubernetes 1.19.3-do.0

### ISSUE THREAD

**Issue by saul-gush** [digitalocean/marketplace-kubernetes#172]
The monitoring stack is failing to install. I even created a new cluster to test this and it failed to install on the new cluster. 

![image](https://user-images.githubusercontent.com/63714857/97769767-9c99d800-1b25-11eb-9f2f-a71c0e6e4fa7.png)

I tried to install helm charts myself and there is an issue with persistent storage:
```
helm install metrics bitnami/metrics-server -n monitoring
helm upgrade metrics bitnami/metrics-server --set apiService.create=true -n monitoring
helm install prom stable/prometheus -n monitoring
helm install grafana bitnami/grafana -n monitoring
```

Grafana pod error:
mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied

Prometheus pod error
```
level=info ts=2020-10-31T02:54:36.494Z caller=main.go:343 msg="Starting Prometheus" version="(version=2.20.1, branch=HEAD, revision=983ebb4a513302315a8117932ab832815f85e3d2)"
level=info ts=2020-10-31T02:54:36.494Z caller=main.go:344 build_context="(go=go1.14.6, user=root@7cbd4d1c15e0, date=20200805-17:26:58)"
level=info ts=2020-10-31T02:54:36.494Z caller=main.go:345 host_details="(Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 prom-prometheus-server-76cc8fd49c-2rpnm (none))"
level=info ts=2020-10-31T02:54:36.494Z caller=main.go:346 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-31T02:54:36.494Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-10-31T02:54:36.494Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7fff5edcb37e, 0x5, 0x14, 0x30898a0, 0xc0007819b0, 0x30898a0)
	/app/promql/query_logger.go:117 +0x4cd
main.main()
	/app/cmd/prometheus/main.go:374 +0x4f08
```

**Comment by kmpartner** [comment]
I got similar problems previously.
By modifying a tutorial blog post in DigitalOcean, I made a similar monitoring stack using Prometheus. 
Using code in forked repository of this one (https://github.com/kmpartner/marketplace-kubernetes/tree/master/stacks/k8s-monitor-volume), 
You may be able to install a similar monitoring stack by executing deploy.sh at k8s-monitor-volume directory.

I am very happy if I get feedbacks when this one helps to install monitoring stack. 
Now I am trying to make a monitoring stack with helm.

**Comment by joschne** [comment]
@kmpartner 
> Now I am trying to make a monitoring stack with helm.

Not sure, but this may be of interest for you: [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack)

**Comment by kmpartner** [comment]
Thank you for your comment.
I made a prometheus monitoring stack using helm at my forked repository of this one
https://github.com/kmpartner/marketplace-kubernetes/tree/master/stacks/monitoring
