### ISSUE TITLE
Kubernetes Monitoring Stack is not persistent

### ISSUE THREAD

**Issue by dron-alterpost** [digitalocean/marketplace-kubernetes#175]
All changes made in Grafana are lost on pod recreation.
It would be pretty good to have simple way to add PVC. For now Kubernetes Monitoring Stack cannot be used on production environment because all changes in grafana can be lost.

**Comment by paulanunda** [comment]
Total agree. I've added a 10gb PVC to the Grafana deployment so that changes can be persisted.
