### ISSUE TITLE
Can we run a script on all nodes prior to installing our application into the cluster? 

### ISSUE THREAD

**Issue by watcher00090** [digitalocean/marketplace-kubernetes#202]
Hi,

We're looking to have some packages present on all nodes prior to installing our k8s application into the cluster. Since deploy.sh is run on the master, is there any way to access the ip addresses of all nodes in deploy.sh, or if not, is there some script that we can add to our stack that is guaranteed to be run on all nodes, prior to the running of deploy.sh? 

Thank you,
James Pedersen

**Comment by paulanunda** [comment]
Unfortunately we don't offer a way to modify worker nodes.

**Comment by watcher00090** [comment]
Do you have a plan to offer it sometime in the future, though? It's important for our k8s application to have the nfs-common or the nfs-utils package preinstalled on the worker nodes......
