### ISSUE TITLE
Proposal: Add KubeSphere to DigitalOcean Marketplace (Kubernetes)

### ISSUE THREAD

**Issue by FeynmanZhou** [digitalocean/marketplace-kubernetes#213]
Hi DOK Team and @marketplace-eng:

KubeSphere is an open-source container platform based on Kubernetes. Users are allowed to easily install KubeSphere on DigitalOcean Kubernetes to build an enterprise-grade container platform with full-stack automated IT operations and streamlined DevOps workflows.

- KubeSphere Website: https://kubesphere.io/
- KubeSphere Github: https://github.com/kubesphere/
- KubeSphere on AWS Quickstart (Integrated with EKS): https://aws.amazon.com/quickstart/architecture/qingcloud-kubesphere/
- Install KubeSphere on DigitalOcean Kubernetes: https://kubesphere.io/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do/
- Use KubeSphere to Manage DigitalOcean Kubernetes and Amazon EKS: https://thenewstack.io/tutorial-use-kubesphere-to-manage-digitalocean-kubernetes-and-amazon-eks/

Hope the materials above are helpful. If this proposal could be approved by DO Marketplace Team, we would like to create a PR to add KubeSphere to the marketplace and maintain it in the long term : )

**Comment by keladhruv** [comment]
Hi @FeynmanZhou,
Thanks for reaching out and sharing the relevant documentation. KubeSphere would be a great value addition to the DigitalOcean Customers.

Please feel free to create a PR. 
[CONTRIBUTING.md](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md)

Looking forward to having you on DigitalOcean Marketplace! :)

**Comment by FeynmanZhou** [comment]
@keladhruv Thanks Dhruv! We will create a PR soon.

**Comment by jgannondo** [comment]
I see a PR has been submitted: https://github.com/digitalocean/marketplace-kubernetes/pull/225 so I will close this issue. We hope to have the PR reviewed soon. Thanks!
