### ISSUE TITLE
Are the steps in the marketplace correct?

### ISSUE THREAD

**Issue by Setti7** [digitalocean/marketplace-kubernetes#22]
As a begginner trying out kubernetes I'm having trouble setting up the Kubernetes Monitoring Stack (BETA) from the market place.

I'm following all the steps: creating a cluster with 2 node pools, a load balancer for the pools, and downloading the config file. But, when I run the first command (`kubectl -n prometheus-operator get svc prometheus-operator-grafana`) it does not work  (error: `Error from server (NotFound): services "prometheus-operator-grafana" not found`). Accessing the ip address of the load balancer also does not work, it just gives a 503 Service Unavailable error.

What should I do that I'm not doing? Do I need to install grafana and etc manually? Is there any other resources I could read to get this up and running easily?

**Comment by countingtoten** [comment]
Is kubectl running against the cluster you created or a different cluster?

Try running `kubectl --kubeconfig <path-to-your-kubeconfig> -n prometheus-operator get svc prometheus-operator-grafana`.

If that didn't work run `kubectl --kubeconfig <path-to-your-kubeconfig> get svc -A`. Look for the prometheus-operator-grafana service. It's possible that the install failed.

**Comment by arosales** [comment]
@Setti7 thanks for the trying out the Monitoring Stack and the feedback here. As you get started with Kubernetes on DO be sure to check out how to connect to your cluster:
https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/

Assuming you created the cluster in the DO cloud UI (https://cloud.digitalocean.com/kubernetes/clusters/), you downloaded the Kubernetes config file (something with the name like, monitoring-k8s-1-15-3-do-1-sfo-kubeconfig.yaml) to say ~/Downloads, and you have kubectl installed on your local machine you can also try the following:

```
cp ~/.kube/config  ~/.kube/config.bkup
cp  ~/Downloads/monitoring-k8s-1-15-3-do-1-sfo-kubeconfig.yaml  ~/.kube/config
kubectl -n prometheus-operator get svc prometheus-operator-grafana
```

**Comment by Setti7** [comment]
Thanks! I followed your instructions and it worked. I might have forgotten to rename the config file to "config" or something like that.
