### ISSUE TITLE
Marketplace link in `History of installed applications` is incorrect

### ISSUE THREAD

**Issue by fuziontech** [digitalocean/marketplace-kubernetes#240]
After installing PostHog to K8s cluster using marketplace at the bottom of the K8s cluster page on DigitalOcean the link to PostHog on the Marketplace is incorrect

It is linking to
https://marketplace.digitalocean.com/apps/post-hog <- This 404's as it's an invalid URL
when it should be linking to
https://marketplace.digitalocean.com/apps/posthog-1

![image](https://user-images.githubusercontent.com/391319/125357316-52a3fb80-e31c-11eb-8db8-4b52540129de.png)

PS:
Sorry if this is the wrong spot to open this issue! I'm not sure where else to report it :)

**Comment by keladhruv** [comment]
Thanks for letting us know. I will keep you updated.
