### ISSUE TITLE
helm chart / stack parameter

### ISSUE THREAD

**Issue by kubemq** [digitalocean/marketplace-kubernetes#34]
Hi,
I'm trying to bring KubeMQ (Kubernetes Message Broker) to the marketplace via a helm chart.
In order that KubeMQ will properly install, a token parameter should be passed during deploy,
Can you guide me on how to do so or direct me to the right example/link ?
Thank you,

**Comment by arosales** [comment]
@kubemq,

Thanks for the work on bringing KubeMQ to the DigitalOcean Marketplace.

Does this token need to be dynamic, meaning it needs to be specific to each customer's deploy? Or does can it be general, applicable to all deploys? 

OpenFaas generates a dynamic password on deploy:
https://github.com/digitalocean/marketplace-kubernetes/blob/master/stacks/openfaas/deploy.sh#L8

If your using a non-standard package from a base container image we may need to add this to the base image.

Let us know if this helps, and more details on the token generation and passing during deploy.

**Comment by kubemq** [comment]
The Token should be dynamic as bring your license type of installation

**Comment by kubemq** [comment]
Just make sure we are aligned.
The user should register on our site and get a Token,
with this  Token he needs to deploy KubeMQ.
Another way would be fine for us is if we get the user email address then we can generate a token automatically.

**Comment by arosales** [comment]
@kubemq thanks for the clarification. We currently don't support deploy-time user registration/license-creation for 1-click Kubernetes apps.

Kubemq would need to do the register and license set after initial deploy. Ideally there is a trial period of base functionality provided to the user while they registers directly with kubemq and obtains a license.

Let me know if you have any further questions, and thanks for your work to list kubemq on the DigitalOcean Marketplace.

**Comment by kubemq** [comment]
We have an idea and i just to make sure this is fine with you.
Since you deploy with stacks using kubectl, we can do kubectl apply -f with a url from our server that will generate the required parameters and deploy. yes ?
We don't need a mandatory helm chart..... ?
