### ISSUE TITLE
 Kubernetes Monitoring Stack failed to install in Kubernetes v1.20.2-do.0

### ISSUE THREAD

**Issue by rparthi-pdf** [digitalocean/marketplace-kubernetes#352]
I am trying to install the Kubernetes Monitoring Stack addon from cloud portal but it getting failed. Please provide any idea to resolve this error and steps to install the Kubernetes Monitoring Stack in cluster.

**Comment by bimlas** [comment]
Same issue here, trying to install Kubernetes Monitoring Stack (`kube-prometheus-stack`) 1-Click App, but it's constantly drops "Installation failed - Version 35.5.1" messages. I added extra nodes to the cluster but it does not helped. Where can I watch the logs of installation to get some clue about the problem?
