### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by devdattakulkarni** [digitalocean/marketplace-kubernetes#512]
On the README there is link to Kubernetes 1-click apps. (This line: You can find more information about DigitalOcean Kubernetes how to use 1-Click apps in our [Kubernetes Documentation](https://docs.digitalocean.com/products/kubernetes/quickstart/#install-a-1-click-app-to-a-new-or-existing-kubernetes-cluster)

The above link is broken. It gives 404 error.

**Comment by msannan2** [comment]
Hey @devdattakulkarni thanks for pointing it out. Updated.

**Comment by msannan2** [comment]
Closing this issue
