### ISSUE TITLE
Old version of OpenEBS is showing on DIgitalocean market place.

### ISSUE THREAD

**Issue by ChandanSagar** [digitalocean/marketplace-kubernetes#55]
I can see OpenEBS 1.3 has been updated on Digitalocean market place.
When installing OpenEBS from the market place it's installing 1.3.0 version.
But it seems there still some places where it's still showing 1.1 version of OpenEBS.
I have attached a few screenshots for reference.

![digitalocean-3](https://user-images.githubusercontent.com/27363164/68104975-198a7580-ff03-11e9-9414-59e1187ab67d.JPG)
![digitalocean-2](https://user-images.githubusercontent.com/27363164/68104976-198a7580-ff03-11e9-98ba-1ee06abbc1b8.png)
![digitalocean-1](https://user-images.githubusercontent.com/27363164/68104977-1a230c00-ff03-11e9-93a2-15639719eb35.png)

**Comment by paulanunda** [comment]
Thanks for catching this @ChandanSagar; the fix has been pushed.

**Comment by ChandanSagar** [comment]
Hi @paulanunda , thanks for the fix. One small change required, in the software included section version 1.3.0 is redirecting to openebs 1.1.0 release tag (https://github.com/openebs/openebs/releases/tag/1.1.0). 
It should redirect to https://github.com/openebs/openebs/releases/tag/1.3.0
Attached screenshot for your reference.

![image](https://user-images.githubusercontent.com/27363164/68285397-39599f00-00a5-11ea-9b31-ed650e3918e5.png)

**Comment by paulanunda** [comment]
Thanks again @ChandanSagar; it has been fixed.

**Comment by ChandanSagar** [comment]
Thanks for the fix @paulanunda .
