### ISSUE TITLE
[metrics-server] unable to fully scrape metrics from source

### ISSUE THREAD

**Issue by arosales** [digitalocean/marketplace-kubernetes#93]
_User reported:_

> After installing I get an error message in the pod logs of metrics server:
> 
> `unable to fully scrape metrics from source kubelet_summary:default-ji17: unable to fetch metrics from Kubelet default-ji17 (10.133.247.135): Get https://10.133.247.135:10250/stats/summary?only_cpu_and_memory=true: x509: cannot validate certificate for 10.133.247.135 because it doesn't contain any IP SANs`
> 
> I could run the metrics server with the flag --kubelet-insecure-tls But I think the one click install should just work with the current settings?

**Comment by scottcrawford03** [comment]
Hey there! Was this being installed on an existing cluster or a new cluster? Also, what is the version of the cluster it was being installed on? Thanks!

**Comment by paulanunda** [comment]
This has been fixed.

**Comment by taxilian** [comment]
I'm having this issue; would be nice for me and maybe others in the future if an explanation of what fixed it were added =]

I am trying to add to an existing 1.19.4 kubeadm cluster

**Comment by lx308033262** [comment]
> I'm having this issue; would be nice for me and maybe others in the future if an explanation of what fixed it were added =]
> 
> I am trying to add to an existing 1.19.4 kubeadm cluster

me too
