### ISSUE TITLE
Recommended way of uninstalling the monitoring stack

### ISSUE THREAD

**Issue by dewey** [digitalocean/marketplace-kubernetes#94]
Hey,

I'm wondering what's the recommended way of rolling back the installation of the monitoring stack so that nothing is left behind? I couldn't find anything in the marketplace description.

Thank you!

**Comment by NikolaiGulatz** [comment]
You can probably just delete the "prometheus-operator" namespace which will also delete all the resources deployed there

**Comment by dewey** [comment]
That's what I did now, just expected some UI option that's somewhere close to the installing step. Thanks for confirming. Will close this now, maybe it helps someone in the future.

**Comment by ismailyenigul** [comment]
You need to delete some services from kube-system namespace too
```apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-coredns
  labels:
    app: prometheus-operator-coredns
    jobLabel: coredns

    chart: prometheus-operator-8.2.0
    release: "prometheus-operator"
    heritage: "Tiller"
  namespace: kube-system
spec:

....
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-proxy
  labels:
    app: prometheus-operator-kube-proxy
    jobLabel: kube-proxy

    chart: prometheus-operator-8.2.0
    release: "prometheus-operator"
    heritage: "Tiller"
  namespace: kube-system

kubectl get services -A 
...
kube-system            metrics-server                                 ClusterIP      10.25.228.222   <none>          443/TCP                      127d
kube-system            prometheus-operator-coredns                    ClusterIP      None             <none>          9153/TCP                     127d
kube-system            prometheus-operator-kube-controller-manager    ClusterIP      None             <none>          10252/TCP                    127d
kube-system            prometheus-operator-kube-etcd                  ClusterIP      None             <none>          2379/TCP                     127d
kube-system            prometheus-operator-kube-proxy                 ClusterIP      None             <none>          10249/TCP                    127d
kube-system            prometheus-operator-kube-scheduler             ClusterIP      None             <none>          10251/TCP
```

**Comment by dsabi** [comment]
There is also a service not included in that release of "prometheus-operator", called "prometheus-operator-kubelet"

**Comment by GregCKrause** [comment]
Considering these were [installed via helm](https://github.com/digitalocean/marketplace-kubernetes/blob/master/stacks/monitoring/deploy.sh), I decided to uninstall them with helm as well.

`
helm uninstall prometheus-operator -n prometheus-operator
helm uninstall metrics-server -n kube-system
`

**Comment by adamhenson** [comment]
Seems like this is a missing feature. It's easy to install via 1 click in the UI, but considering the resources this stack consumes or any stack that is installed via marketplace... it should be just as easy to uninstall. Otherwise, you subject the user to cost (is this intentional?)

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah, how can I uninstall one app again?
