### ISSUE TITLE
Grafana Plugins and missing Pie Chart plugin

### ISSUE THREAD

**Issue by andyjk15** [digitalocean/marketplace-kubernetes#97]
Hi, 
Recently spun up a Kubernetes cluster and install this monitoring stack. While looking through the dashboards there are a few that are claiming to be missing the Pie Chart plugin (Kubernetes / Networking / Cluster). An FYI.

Also, how do you install new plugins as I cannot exec into the pod? - in case users want to add new plugins

Thanks

**Comment by paulanunda** [comment]
Hi @andyjk15, could you provide a screenshot? I'm not seeing the missing Pie Chart plugin error in `Kubernetes / Networking / Cluster`

**Comment by paulanunda** [comment]
Closing due to no response.
